In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./imagenet-superclasses.txt", names=["superclass"], sep="\t")

df

                  superclass
0    cyprinid, cyprinid fish
1    cyprinid, cyprinid fish
2             mackerel shark
3              requiem shark
4                      shark
..                       ...
995                   fungus
996                   fungus
997                   fungus
998                    fruit
999     tissue, tissue paper

[1000 rows x 1 columns]

In [8]:
df["count"] = 1

In [3]:
df[df.superclass == "truck, motortruck"].index

Index([555, 569, 717, 864, 867], dtype='int64')

In [15]:
df.groupby(by="superclass").agg("count").sort_values(by="count", ascending=False)

                                          count
superclass
terrier                                      18
hound, hound dog                             12
shepherd dog, sheepdog, sheep dog            10
car, auto, automobile, machine, motorcar     10
ball                                          9
...                                         ...
basidiomycete, basidiomycetous fungi          1
venomous lizard                               1
viper                                         1
wall unit                                     1
warship, war vessel, combat ship              1

[551 rows x 1 columns]